# Generated by Django 5.1.4 on 2025-11-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transportcompany_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportcompany',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='transportcompany',
            name='number_of_vehicles',
        ),
        migrations.RemoveField(
            model_name='transportcompany',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='transportcompany',
            name='support_email',
        ),
        migrations.RemoveField(
            model_name='transportcompany',
            name='vehicle_type',
        ),
        migrations.CreateModel(
            name='HostTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpoint', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('departure_time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route_description', models.TextField(blank=True, null=True)),
                ('assigned_bus', models.ImageField(blank=True, null=True, upload_to='bus_images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_trips', to='users.transportcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='reservation_vehicle_images/')),
                ('customer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reservation_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.route')),
            ],
        ),
    ]
