# Generated by Django 5.1.4 on 2025-11-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_transportcompany_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
