# Generated by Django 4.2.27 on 2026-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transportcompany_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttrip',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
