# Generated by Django 4.2.27 on 2026-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_hosttrip_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
